export const descObject={
    0:"Clear sky",
    1:"Mainly clear",
    2:"Partly cloudy",
    3:"Overcast",
    45:"Fog",
    48:"Depositing rime fog (freezing fog)",
    51:"Light drizzle",
    53:"Moderate drizzle",
    55:"Dense, intense drizzle",
    56:"Light freezing drizzle",
    57:"Dense, intense freezing drizzle",
    61:"Light rain",
    63:"Moderate rain",
    65:"Heavy rain",
    66:"Light freezing rain",
    67:"Heavy freezing rain",
    71:"Light snow",
    73:"Moderate snow",
    75:"Heavy snow",
    77:"Grainy? snow (what the fuck is 'grainy' snow?)",
    80:"Light showers",
    81:"Moderate showers",
    82:"Heavy showers",
    95:"Thunderstorm",
    96:"Mega thunderstorm",
    98:"Fucking mental thunderstorm with hail and stuff"
}